### ISSUE TITLE
Unexpected shutdown

### ISSUE THREAD

**Issue by TimoGlastra** [animo/animo-demo#10]
I think this is the cause: https://github.com/animo/animo-demo/blob/25c08a5d639666608423e687b1cc76eabaa335d8/server/src/index.ts#L68-L89

We should add error handling (catch) to this method and also add a generic uncaught promise rejections handler: https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html to prevent the server from crashing

```
undefined:1
{"@t

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.fromString (/www/node_modules/@aries-framework/core/build/utils/JsonEncoder.js:45:21)
    at Function.fromBuffer (/www/node_modules/@aries-framework/core/build/utils/JsonEncoder.js:61:28)
    at Function.fromBase64 (/www/node_modules/@aries-framework/core/build/utils/JsonEncoder.js:29:28)
    at Function.fromUrl (/www/node_modules/@aries-framework/core/build/modules/connections/messages/ConnectionInvitationMessage.js:79:62)
    at /www/build/index.js:64:73
    at Generator.next (<anonymous>)
    at /www/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/www/build/index.js:4:12)
```

**Comment by janrtvld** [comment]
Most of the code was used for testing with proof qr-code and can be removed.

**Comment by TimoGlastra** [comment]
#12 doesn't fix the issue with the unexpected shutdown as it doesn't add a catch / unhandled promise rejection handler
