### ISSUE TITLE
Getting Error while setting up project

### ISSUE THREAD

**Issue by SyedImam1998** [animo/animo-demo#172]
Hi team,

I am trying to setup the project but i am getting this error while give cmd:
`yarn install`

Error:
![image](https://github.com/animo/animo-demo/assets/52135949/b794aa53-fbc0-4835-8db3-1a9e72ddf017)

**Comment by janrtvld** [comment]
Hi! It looks like it cannot find libindy. This is a native library required for hosting the demo.

Hopefully this guide can help you: https://aries.js.org/guides/getting-started/installation/nodejs

**Comment by SyedImam1998** [comment]
Hey @janrxyz ,

I followed all steps that were mentioned but still getting error.


Step-1: Node Setup:

![image](https://github.com/animo/animo-demo/assets/52135949/f590f61d-94f3-4578-b6fc-4a965e1a97de)


Step-2: Npm / Yarn Setup:

![image](https://github.com/animo/animo-demo/assets/52135949/47176ad3-4d05-4c56-9983-5c529c05d59b)

Step-3: Download Indy-sdk and Adding  Path 

![image](https://github.com/animo/animo-demo/assets/52135949/0bf8da0f-9258-4229-92c6-15dd82973bf8)

![image](https://github.com/animo/animo-demo/assets/52135949/3f9f0920-db7c-48a2-ac4b-7fbe0fc5be16)

Step-4: Confirm installation

run cmd;
`npx -p @aries-framework/node@^0.3 is-indy-installed`

I ran it....

when i tried to give same cmd it is asking me install again. But Y again...?

![image](https://github.com/animo/animo-demo/assets/52135949/cbc16168-1ee8-469e-b9d1-5737cc98bf1b)

**Comment by janrtvld** [comment]
You installed Libindy, the underlying package needed to run AFJ. If you run the final command, it installs AFJ and checks if Libindy installation has succeeded.

**Comment by SyedImam1998** [comment]
I am getting this error when i gave yarn install can some one help me


```
yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lensesio/cypress-websocket-testing@1.0.1" has incorrect peer dependency "rxjs@^6.5.0".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > qrcode.react@1.0.1" has incorrect peer dependency "react@^15.5.3 || ^16.0.0 || ^17.0.0".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > postcss-loader@7.0.1" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > server > routing-controllers@0.9.0" has unmet peer dependency "class-transformer@^0.3.1".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > server > routing-controllers@0.9.0" has unmet peer dependency "class-validator@^0.12.2".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > kbar > react-virtual@2.10.4" has incorrect peer dependency "react@^16.6.3 || ^17.0.0".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > server > ts-node-dev > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-fc13f99e-a41a-44a9-977d-444e91fd4d5b > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
[4/4] Building fresh packages...
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
error C:\Users\ACER\Desktop\animo-demo\node_modules\indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\ACER\Desktop\animo-demo\node_modules\indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.16.0 | win32 | x64
gyp info find Python using Python version 3.11.3 found at "C:\Users\ACER\AppData\Local\Programs\Python\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2022 (17.6.33723.286) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\ACER\Desktop\animo-demo\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ACER\\Desktop\\animo-demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ACER\Desktop\animo-demo\node_modules\indy-sdk
```

**Comment by janrtvld** [comment]
You need to follow the steps from the stacktrace: https://github.com/nodejs/node-gyp#on-windows

**Comment by SyedImam1998** [comment]
I have followed it and installed the Desktop with C++ in visual Studio 2019 but still getting the same error.

**Comment by janrtvld** [comment]
Have you tried reinstalling the dependencies and/or re-creating the yarn.lock after your changes? Make sure that it refers to the most recent installation of visual studio.

**Comment by SyedImam1998** [comment]
I have re-cloned the repo. I am getting the same error.

```
D:\animo-demo\client> yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lensesio/cypress-websocket-testing@1.0.1" has incorrect peer dependency "rxjs@^6.5.0".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > qrcode.react@1.0.1" has incorrect peer dependency "react@^15.5.3 || ^16.0.0 || ^17.0.0".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > postcss-loader@7.0.1" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > server > routing-controllers@0.9.0" has unmet peer dependency "class-transformer@^0.3.1".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > server > routing-controllers@0.9.0" has unmet peer dependency "class-validator@^0.12.2".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > kbar > react-virtual@2.10.4" has incorrect peer dependency "react@^16.6.3 || ^17.0.0".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > server > ts-node-dev > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-26b36de9-dfe3-4906-b3a8-31bbb530ba97 > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
[4/4] Building fresh packages...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[7/7] ⠁ ffi-napi
error D:\animo-demo\node_modules\indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\animo-demo\node_modules\indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.16.0 | win32 | x64
gyp info find Python using Python version 3.11.3 found at "C:\Users\ACER\AppData\Local\Programs\Python\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2022 (17.6.33723.286) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\animo-demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\animo-demo\node_modules\indy-sdk
```

**Comment by janrtvld** [comment]
Could you run `npm config set msvs_version 2019 --global`? NPM is probably not able to locate the correct Visual Studio installation.

**Comment by SyedImam1998** [comment]
> Could you run `npm config set msvs_version 2019 --global`? NPM is probably not able to locate the correct Visual Studio installation.

Hey @janrxyz  I have done it but got same error.

```
PS D:\animo-demo> npm config set msvs_version 2019 --global
PS D:\animo-demo> yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lensesio/cypress-websocket-testing@1.0.1" has incorrect peer dependency "rxjs@^6.5.0".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > qrcode.react@1.0.1" has incorrect peer dependency "react@^15.5.3 || ^16.0.0 || ^17.0.0".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > postcss-loader@7.0.1" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > server > routing-controllers@0.9.0" has unmet peer dependency "class-transformer@^0.3.1".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > server > routing-controllers@0.9.0" has unmet peer dependency "class-validator@^0.12.2".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > kbar > @reach/portal@0.16.2" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > kbar > react-virtual@2.10.4" has incorrect peer dependency "react@^16.6.3 || ^17.0.0".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > server > ts-node-dev > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-6e603cfe-9ece-4055-b3fc-c81adfb05365 > client > kbar > @reach/portal > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
[4/4] Building fresh packages...
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[7/7] ⠁ ffi-napi
error D:\animo-demo\node_modules\indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\animo-demo\node_modules\indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.16.0 | win32 | x64
gyp info find Python using Python version 3.11.3 found at "C:\Users\ACER\AppData\Local\Programs\Python\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2022 (17.6.33723.286) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\animo-demo\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\animo-demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\animo-demo\node_modules\indy-sdk

```
